# Generated by Django 4.1.2 on 2022-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=10)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_branch', models.CharField(default='BCA', max_length=10)),
            ],
        ),
    ]
